services:
  db:
    image: mariadb:11.7.2
    container_name: mariadb_dev
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mysql_migration_error_dev
      MARIADB_USER: app
      MARIADB_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-prootpassword",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: phoenix_app
    environment:
      PHX_SERVER: "true"
      PORT: "4000"
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: mysql_migration_error_dev
      DB_USER: app
      DB_PASSWORD: apppass
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "
        mix deps.get &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "

volumes:
  mariadb_data:
  deps:
  build:
